# Generated by Django 4.0.3 on 2022-04-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='mail',
            field=models.CharField(default=2, max_length=20, verbose_name='Mail'),
            preserve_default=False,
        ),
    ]
