# Generated by Django 4.0.3 on 2022-04-21 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_pub_chat_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub_chat',
            name='msg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
